version: '3.8'

services:
  agent:
    image: portainer/agent:2.21.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - internal-network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer-ce:2.21.3
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - internal-network
      - external-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.proxy == true
      labels:
        # core
        - traefik.enable=true
        - traefik.docker.network={{ external_network_name }}
        # http
        - traefik.http.routers.portainer.rule=Host(`{{ portainer_http_route }}`)
        - traefik.http.routers.portainer.entrypoints=web_insecure
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.http.routers.portainer.service=portainer

networks:
  internal-network:
    driver: overlay
    internal: true
    name: "{{ internal_network_name }}"
  external-network:
    driver: overlay
    internal: false
    name: "{{ external_network_name }}"

volumes:
  portainer_data:
